AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an Oracle RDS instance.

Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: MigrationOracleDB
    Description: The database instance identifier.

  DBName:
    Type: String
    Default: oracledb
    Description: The name of the database to create.

  DBInstanceClass:
    Type: String
    Default: db.t3.small
    Description: The RDS instance type.

  AllocatedStorage:
    Type: Number
    Default: 20
    Description: The allocated storage size in GB.

  EngineVersion:
    Type: String
    Default: 19.0.0.0.ru-2024-10.rur-2024-10.r1
    Description: The Oracle database engine version.

  MasterUsername:
    Type: String
    Default: admin
    NoEcho: true
    Description: The master username for the database.

  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: The master user password for the database.

  MultiAZ:
    Type: String
    Default: true
    Description: Specifies if the database instance is a Multi-AZ deployment.

  BackupRetentionPeriod:
    Type: Number
    Default: 7
    Description: The number of days to retain backups.
    
  StorageType:
    Type: String
    Default: gp3
    Description: StorageType
    
  Iops:
    Type: Number
    Default: 20000
    Description: Iops
    
  StorageThroughput:
    Type: Number
    Default: 4000
    Description: StorageThroughput
    
    
  PerformanceInsightsRetentionPeriod:
    Type: Number
    Default: 7
    Description: PerformanceInsightsRetentionPeriod
    

  PreferredBackupWindow:
    Type: String
    Default: "03:00-06:00"
    Description: PreferredBackupWindow
    
    
  PreferredMaintenanceWindow:
    Type: String
    Default: "Sun:03:00-Sun:04:00"
    Description: PreferredMaintenanceWindow
    
  OptionGroupName:
    Type: String
    Default: "default:oracle-ee-19"
    Description: OptionGroupName
    
    
  CACertificateIdentifier:
    Type: String
    Default: "rds-ca-rsa4096-g1"
    Description: CACertificateIdentifier



Resources:
  OracleRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      VpcId: !ImportValue MigrationVPC
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/16
          
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Oracle RDS instance
      SubnetIds:
        - !ImportValue MigrationPrivateSubnetA
        - !ImportValue MigrationPrivateSubnetC
        - !ImportValue MigrationPrivateSubnetE
          
  OracleRDSParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: "Parameter group for Oracle RDS"
      Family: "oracle-ee-19"
      Parameters:
        optimizer_mode: "ALL_ROWS"
        open_cursors: "300"
        cursor_sharing: "FORCE"
          
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: oracle-ee
      EngineVersion: !Ref EngineVersion
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBInstanceClass: !Ref DBInstanceClass
      StorageType: !Ref StorageType
      AllocatedStorage: !Ref AllocatedStorage
      Iops: !Ref Iops
      StorageThroughput: !Ref StorageThroughput
      StorageEncrypted: true
      MultiAZ: !Ref MultiAZ
      NetworkType: IPv4
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      VPCSecurityGroups: !Ref OracleRDSSecurityGroup
      CACertificateIdentifier: !Ref CACertificateIdentifier
      Port: 1521
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: !Ref PerformanceInsightsRetentionPeriod
      PerformanceInsightsKMSKeyId: alias/aws/rds     
      DBName: !Ref DBName
      DBParameterGroupName: !Ref OracleRDSParameterGroup
      OptionGroupName: !Ref OptionGroupName
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      KmsKeyId: alias/aws/rds
      CopyTagsToSnapshot: true
      EnableCloudwatchLogsExports:
        - "alert"
        - "audit"
        - "listener"
        - "trace"     
      DeletionProtection: false
      
      
Outputs:
  RDSInstanceEndpoint:
    Description: The connection endpoint for the RDS database instance.
    Value: !GetAtt RDSInstance.Endpoint.Address

  RDSInstancePort:
    Description: The port for the RDS database instance.
    Value: !GetAtt RDSInstance.Endpoint.Port
